return { --[[{ "goto", 44+1 },]]"You wake up in a warm grass filled field.[audio=sfx=grass1] A cow [audio=sfx=grass2]approac[audio=sfx=grass3]hes.",
  "What would you like to do?",
  { "choice", { "Offer the cow a sandwich.", 82 }, { "Moo at the cow.", 7 }, },
  "[audio=sfx=emptyBag][pause=0.5] What sandwich? You just woke up! You have nothing on you.",
  "The cow stares down at you as you're checking your pockets.",
  { "goto", 2 },
  "[audio=sfx=moo]You moo at the cow![pause=0.85] The cow is very impressed!",
  "It let's out a delighted 'Moooo' which[newline] sounds suspiciously like an applause.",
  "The cow then nudges you gently with its[newline]    head, indicating you should follow it.",
  { "choice", { "Follow the surprisingly appreciative cow.", 11 }, { "Politely decline and try to remember how you got here.", 47 }, },
  "As you're walking along side the cow, it glances over and stops.",
  "It lets out a mournful 'Mooo...' that seems[newline] to imply deep existential disappointment.",
  "Suddenly, the cow pulls a small,[audio=sfx=pullout] slightly chewed, triangular,[newline]    sandwich from seemingly nowhere and offers it to you.",
  { "choice", { "Accept the mysterious cow sandwich.", 15 }, { "Politely decline, suspecting bovine trickery.", 18}, },
  { "inventory", "sandwich", true },
  "You take the mysterious[audio=sfx=pickup] sandwich and put it into[newline]your pocket. It smells faintly of grass and...[pause=0.1] regret?",
  { "goto", 19 },
  "You politely decline. The cow sighs, a sound[newline]that seems to carry the weight of the world.",
  "[pause=2] You continue following the cow for hours.[newline]Endless grass fields stretch into the horizon.",
  "As you stare at the horizon for anything, you[newline]  come to realise the cow has disappeared.",
  "  You look around and all that can be found is a small[newline]blue mushroom growing between the blades of grass.",
  { "choice", { "Close your eyes.", 23 }, { "Poke the small blue mushroom.", 26 }, { "Pick the small blue mushroom", 34 } },
  "\0\0\0\0\0\0\0\0 \0\0\0\0\0 \0\0 \0\0\0 \0\0\0\0 \0\0\0 \0\0 \0\0\0 \0\0\0 \0[pause=2][newline]You open your eyes again, wondering if you missed any text.",
  "The field seems slightly... blurrier? Or [newline]perhaps that's just your imagination.",
  { "goto", 21 },
  "The mushroom disap[audio=sfx=pop]pears as you touch it.",
  "In its place, a single, perfectly[audio=sfx=fizz] ripe strawberry appears.",
  { "choice", { "Eat the mysterious strawberry.", 29 }, { "Pocket the strawberry.", 31 }, },
  "  You cautiously eat the strawberry[audio=sfx=eat]. It[newline]tastes surprisingly like[pause=0.5] disappointment.",
  { "goto", 54},
  "You pocket the strawberry, wondering if it holds any secrets.",
  { "inventory", "strawberry", true },
  { "goto", 54 },
  "You reach out, and grasp the small blue[newline]mushroom. You put[audio=sfx=pickup] it into your pocket.",
  { "inventory", "blue_mushroom", true },
  "You look at your hand, and it has turned[newline]    blue from touching the mushroom.",
  "Suddenly, you feel an overwhelming urge to paint everything blue.",
  { "choice", { "Try to resist the urge.", 39 }, { "Embrace the blueness and look for something to paint.", 41 }, },
  "You manage to suppress the urge, but[newline]  your hand remains stubbornly blue.",
  { "goto", 50 },
  "Your gaze falls upon a nearby rock. It wasn't there before.",
  "It looks like it could use a splash of bright blue paint!",
  { "choice", { "Paint the nearby rock blue.", 44 }, { "Decide that painting is for another day.", 39 }, },
  { "function", function() love.graphics.setBackgroundColor(0,0,.1,1) end, },
  "You enthusiastically rub your blue hand[newline][audio=sfx=paint] against the rock. It is now slightly bluer",
  { "goto", 50 },
  "Your head starts to hurt as you try to think how you got here.",
  "You try to shake this feeling off, but something feels wrong.",
  { "goto", 21 },
  "You notice something peculiar as you turn back around.",
  "The grass seems to have taken on a slightly more vibrant shade of[newline]    green. Almost as if it's pleased with the concept of blueness.",
  "The grass starkly starts to squawk,[audio=sfx=grass] resonating[newline]      with the faint blue tinge on your hand.",
  { "goto", 58 },
  "A sudden gust of wind sweeps across the[newline]   field, almost blowing you off your feet.",
  "The air shimmers for a moment, and you hear a faint whisper.",
  "'The fruit of existential quandaries ripens in unexpected places.'",
  "[pause=1] You ponder this profound (or possibly nonsensical) statement.",
  "  As the strange sensations subside,[newline]you look around the field once more.",
  "    The cow has reappeared, now wearing a pair of[newline]oversized spectacles perched precariously on its nose.",
  "It looks at you with an air of scholarly contemplation.",
  " The cow clears its throat (a surprisingly dignified[newline]sound) and speaks, its voice a low, gentle rumble.",
  "'Ah, yes. The planned deviation has reached its planned conclusion.'",
  { "choice", { "Ask the cow what it means.", 65 }, { "Nod sagely as if you understood perfectly.", 68 }, },
  "You manage to catch up to the cow. Asking the cow what it means.",
  "'My dear participant,' the cow continues, adjusting its spectacles,[newline]          'you have successfully experienced a minor Tuesday.'",
  "'The purpose was...[pause=0.3] well, even I'm not entirely[newline]   sure. But wasn't it delightfully unplanned?'",
  { "goto", 72 },
  "You nod with an air of profound understanding, even though[newline]        you haven't got the foggiest idea what just happened.",
  "The cow seems satisfied with your response and ambles[newline]  off, presumably to plan its next unplanned encounter.",
  { "choice", { "Rub your brow, being glad it is over.", 71 }, { "Chase after the cow and find out what it actually meant.", 64}, },
  "'Oh yes!', the cow sharply turns around. 'Almost forgot'",
  "     The cow produces a tiny,[audio=sfx=pullout] perfectly[newline]folded certificate and presents it to you.",
  "It reads: 'Certificate of Mildly Unplanned Participation.'[audio=sfx=endChime]",
  "You look back up after reading it.[newline]  The sun is setting over the field.",
  "Would you like to fall asleep?",
  { "choice", { "Rest your head (restart)", 77 }, { "Continue wandering through the field.", 79} },
  "You slowly lay down, and drift off.[audio=sfx=wakeup]",
  { "restart" },
  "[pause=1] As you walk, you think to yourself",
  "'Perhaps this really was made in 6 hours'[pause=2]",
  { "goto", 9999 }, -- the end
  { "has", "sandwich", 83, 4 },
  "The cow is stunned. It pulls out an identical sandwich.",
  "It looks at your sandwich, then at its own, then back[newline]  at you with a raised (perhaps imaginary) eyebrow.",
  "'Well, this is getting a bit repetitive, isn't it?'[newline]   it moos, with a hint of world-weariness.",
  { "goto", 2 }
}